### ISSUE TITLE
Example of job script for executing parallel version

### ISSUE THREAD

**Issue by ardifauzi** [jagurs-admin/jagurs#2]
Could you please provide the example of job script for executing parallel version in a single ordinary computer? I tried several times but still failed. Thank you.

**Comment by jagurs-admin** [comment]
Hello, 
Your machine environment is not a batch system like a PC cluster but a single Linux machine, right?
Which do you use thread parallel(OpenMP) or process parallel(MPI)?
If you run jagurs program on a single machine, I recommend OpenMP.

**Comment by ardifauzi** [comment]
Yes, I use Linux operating system and currently I am using MPI.
I will try to use OpenMP. Thank you for your recommendation.

**Comment by jagurs-admin** [comment]
Because it is not necessary to divide topographic data of land and sea if you use OpenMP, file handling is easy.
You may execute a program as follows if you can compile OpenMP program correctly.

$ export OMP_NUM_THREADS=4
$ ./jagurs par=tsun.par > jagurs.log 2>&1

Best regards,

**Comment by ardifauzi** [comment]
Thank you very much. Problem solved!!
