### ISSUE TITLE
マニュアルの誤植

### ISSUE THREAD

**Issue by J-Taniguchi** [jagurs-admin/jagurs#4]
JAGURS-User-Guide.Jp.V0500.pdf中にいくつか誤植を発見しました．

- 9pのtsun.parの記述例　『gridile=』→『grid**f**ile=』
- 17pのCのtsun.parの記述例　『use**r**_linear』→『use_linear=』

**Comment by J-Taniguchi** [comment]
4-4 "NO_WERORDRY_FILE_GIVEN" → "NO_WETORDRY_FILE_GIVEN"

**Comment by jagurs-admin** [comment]
Thank you, Taniguchi-kun, I modified it.
